name: CI - Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificación a ntfy
        run: |
          curl \
            -H "Title: GitHub Actions" \
            -H "Priority: default" \
            -H "Tags: github,white_check_mark" \
            -d "¡CI ejecutado correctamente! 🚀
          Repositorio: ${{ github.repository }}
          Rama: ${{ github.ref_name }}
          Commit: ${{ github.sha }}" \
            https://ntfy.sh/devops-itla